In [3]:
import torch
ckpt_sparse = torch.load('/workspace/tracking_datasets/stark/rand/checkpoints/train/stark_sparse/baseline_got10k_only_sparse/STARKST_ep0001.pth.tar')

In [9]:
ckpt_sparse['net']['transformer.encoder.layers.0.self_attn.q.weight']

tensor([[ 0.0209, -0.0740,  0.0539,  ...,  0.0197, -0.0740,  0.0705],
        [ 0.0580, -0.0706, -0.0499,  ..., -0.0402,  0.0079,  0.0414],
        [ 0.0915, -0.0682,  0.0649,  ...,  0.0844,  0.0575,  0.0217],
        ...,
        [ 0.0360, -0.0999, -0.0020,  ...,  0.0421,  0.0448, -0.0229],
        [-0.0450, -0.0328, -0.1326,  ..., -0.0449, -0.0007,  0.0844],
        [-0.0160,  0.0471,  0.0840,  ...,  0.0181, -0.0244,  0.0558]],
       device='cuda:0')

In [16]:
ckpt_sparse['net']['transformer.encoder.layers.0.self_attn.zeta']

tensor([[[[[0.9999, 0.9991, 0.9993, 0.9998, 0.9990, 0.9992, 1.0003, 0.9992,
            1.0009, 1.0003, 0.9996, 0.9992, 1.0000, 0.9998, 1.0000, 0.9986,
            0.9996, 0.9993, 0.9999, 1.0002, 0.9988, 0.9999, 1.0003, 1.0017,
            0.9994, 0.9999, 0.9997, 0.9999, 0.9996, 1.0001, 0.9998, 0.9995]],

          [[0.9999, 0.9998, 0.9995, 1.0000, 1.0002, 0.9997, 1.0005, 0.9992,
            0.9989, 0.9994, 1.0001, 1.0005, 1.0000, 0.9994, 0.9994, 1.0004,
            0.9998, 0.9985, 0.9998, 1.0002, 1.0008, 1.0008, 0.9991, 0.9995,
            0.9997, 1.0003, 1.0003, 1.0005, 1.0001, 0.9997, 1.0011, 1.0010]],

          [[1.0006, 1.0004, 0.9987, 0.9998, 1.0001, 1.0008, 1.0005, 1.0010,
            0.9989, 0.9988, 0.9992, 1.0001, 1.0012, 0.9995, 1.0003, 0.9993,
            1.0000, 0.9998, 0.9995, 0.9994, 0.9994, 0.9998, 0.9997, 0.9993,
            0.9998, 0.9997, 0.9995, 1.0015, 0.9995, 1.0001, 0.9997, 0.9993]],

          [[0.9997, 1.0002, 1.0000, 1.0007, 1.0005, 1.0008, 1.0014, 1.0005,
   

In [26]:
ckpt_sparse['net']['backbone.0.body.layer2.0.bn1.weight']

tensor([0.2639, 0.1874, 0.2027, 0.2016, 0.2029, 0.2078, 0.2167, 0.1770, 0.1823,
        0.1638, 0.2489, 0.1521, 0.1968, 0.2547, 0.1897, 0.2004, 0.2001, 0.1535,
        0.2110, 0.1407, 0.2052, 0.1701, 0.2409, 0.1673, 0.2550, 0.1277, 0.2348,
        0.1519, 0.3124, 0.2503, 0.1832, 0.1560, 0.1685, 0.1832, 0.2343, 0.1888,
        0.1630, 0.2164, 0.3512, 0.1942, 0.2383, 0.1559, 0.2359, 0.1366, 0.1789,
        0.2183, 0.1845, 0.1801, 0.1408, 0.2376, 0.2027, 0.2411, 0.2099, 0.2116,
        0.1077, 0.1869, 0.2270, 0.2287, 0.1910, 0.1916, 0.2162, 0.2078, 0.2235,
        0.2122, 0.2124, 0.2164, 0.2602, 0.1322, 0.1902, 0.1736, 0.2416, 0.1989,
        0.2038, 0.2216, 0.1763, 0.2176, 0.2127, 0.2316, 0.2531, 0.1652, 0.1626,
        0.1963, 0.2080, 0.1926, 0.2129, 0.2600, 0.1958, 0.1637, 0.2129, 0.3089,
        0.1877, 0.1892, 0.1551, 0.2225, 0.1925, 0.2221, 0.2030, 0.2479, 0.2082,
        0.2479, 0.1451, 0.2120, 0.1959, 0.2158, 0.2166, 0.1843, 0.2348, 0.1779,
        0.2565, 0.2223, 0.2029, 0.1639, 

In [13]:
import torch
ckpt_sparse1 = torch.load('/workspace/tracking_datasets/stark/rand/checkpoints/train/stark_sparse/baseline_got10k_only_sparse/STARKST_ep0011.pth.tar')

In [27]:
ckpt_sparse1['net']['backbone.0.body.layer2.0.bn1.weight']

tensor([0.2642, 0.1878, 0.2024, 0.2014, 0.2031, 0.2079, 0.2168, 0.1772, 0.1823,
        0.1640, 0.2487, 0.1521, 0.1971, 0.2547, 0.1895, 0.2006, 0.2002, 0.1537,
        0.2111, 0.1409, 0.2049, 0.1700, 0.2414, 0.1674, 0.2548, 0.1276, 0.2346,
        0.1522, 0.3123, 0.2507, 0.1830, 0.1564, 0.1687, 0.1833, 0.2338, 0.1886,
        0.1628, 0.2162, 0.3511, 0.1944, 0.2382, 0.1559, 0.2354, 0.1365, 0.1787,
        0.2182, 0.1846, 0.1799, 0.1411, 0.2378, 0.2025, 0.2415, 0.2097, 0.2116,
        0.1079, 0.1870, 0.2271, 0.2289, 0.1909, 0.1913, 0.2160, 0.2076, 0.2235,
        0.2122, 0.2124, 0.2167, 0.2604, 0.1321, 0.1906, 0.1734, 0.2416, 0.1988,
        0.2040, 0.2217, 0.1765, 0.2178, 0.2129, 0.2318, 0.2531, 0.1653, 0.1626,
        0.1963, 0.2076, 0.1924, 0.2127, 0.2596, 0.1955, 0.1636, 0.2133, 0.3091,
        0.1874, 0.1893, 0.1553, 0.2225, 0.1922, 0.2219, 0.2030, 0.2476, 0.2082,
        0.2478, 0.1454, 0.2121, 0.1958, 0.2160, 0.2165, 0.1844, 0.2347, 0.1781,
        0.2562, 0.2227, 0.2027, 0.1642, 

In [14]:
ckpt_sparse1['net']['transformer.encoder.layers.0.self_attn.q.weight']

tensor([[ 0.0198, -0.0722,  0.0536,  ...,  0.0187, -0.0742,  0.0708],
        [ 0.0570, -0.0725, -0.0514,  ..., -0.0401,  0.0067,  0.0411],
        [ 0.0918, -0.0709,  0.0675,  ...,  0.0851,  0.0544,  0.0209],
        ...,
        [ 0.0347, -0.1036, -0.0015,  ...,  0.0442,  0.0426, -0.0215],
        [-0.0464, -0.0296, -0.1336,  ..., -0.0449,  0.0002,  0.0849],
        [-0.0180,  0.0465,  0.0806,  ...,  0.0193, -0.0215,  0.0574]],
       device='cuda:0')

In [17]:
ckpt_sparse1['net']['transformer.encoder.layers.0.self_attn.zeta']

tensor([[[[[0.9973, 0.9981, 1.0016, 0.9970, 0.9991, 0.9982, 0.9998, 0.9998,
            1.0007, 0.9996, 0.9964, 0.9978, 1.0018, 1.0027, 0.9993, 1.0016,
            1.0018, 0.9978, 1.0014, 1.0004, 0.9967, 1.0005, 1.0006, 0.9987,
            0.9973, 0.9970, 1.0017, 1.0005, 1.0009, 0.9997, 0.9981, 0.9992]],

          [[1.0000, 0.9978, 0.9973, 0.9987, 0.9998, 1.0021, 1.0031, 0.9988,
            1.0010, 0.9988, 1.0029, 0.9993, 1.0002, 1.0030, 0.9994, 0.9986,
            0.9974, 0.9949, 1.0023, 0.9981, 0.9992, 1.0041, 0.9998, 0.9941,
            1.0049, 1.0013, 1.0016, 1.0002, 1.0013, 1.0014, 1.0044, 1.0044]],

          [[0.9983, 0.9994, 0.9995, 0.9993, 1.0017, 1.0028, 0.9987, 0.9998,
            0.9985, 1.0000, 0.9990, 0.9997, 1.0025, 0.9987, 1.0007, 0.9971,
            1.0000, 0.9994, 0.9981, 0.9965, 0.9963, 0.9950, 0.9987, 1.0000,
            0.9998, 0.9972, 0.9965, 1.0026, 0.9983, 1.0021, 1.0004, 1.0034]],

          [[0.9999, 1.0022, 0.9971, 0.9996, 1.0010, 1.0023, 1.0055, 1.0014,
   